// apps/nextjs/src/blocks/core/AccordionBlock.tsx
export default function AccordionBlock() {
    return (
        <details>
            <summary>Accordion title</summary>
            <p>Proident voluptate ex est mollit. Sunt mollit excepteur ea ad ut ea id in labore eu tempor pariatur id
                do. Ad veniam ex veniam nulla do nulla amet labore quis do duis labore. Duis culpa reprehenderit commodo
                proident dolor. Pariatur anim nostrud reprehenderit ipsum adipisicing enim nostrud officia consectetur
                labore consequat labore occaecat esse. Minim nisi tempor voluptate ullamco eiusmod aliqua. Qui cupidatat
                culpa Lorem proident pariatur consequat sit excepteur do. Anim est est laborum quis pariatur aute
                proident laboris sunt exercitation ipsum. Dolore quis aliquip occaecat officia non dolore veniam. Velit
                ipsum laboris eu ipsum enim enim anim ea enim id consequat minim tempor velit fugiat. Velit nulla
                nostrud elit ex in in aliquip Lorem laboris minim eiusmod deserunt culpa sit tempor. Eu amet enim sunt
                culpa veniam. In esse esse nisi deserunt quis ea eu ex dolor ut eiusmod non do. Cupidatat non laboris
                qui dolor ea. Aute cillum elit proident dolor sit sit in et sit ad occaecat ut. Eiusmod eu ullamco
                ullamco amet elit ad ad consequat. Sit deserunt in cupidatat non minim aliquip elit. Sint aute elit
                cupidatat fugiat ad. Aliquip est culpa mollit culpa duis laborum commodo sunt ad. Anim in mollit cillum
                amet Lorem anim qui occaecat elit officia esse laborum eu laboris ex.</p>
        </details>
    )
}

// apps/qwik/src/blocks/core/AccordionBlock.tsx
import { component$ } from "@builder.io/qwik";

export default component$(() => {
  return (
    <details>
      <summary>Accordion title</summary>
      <p>
        Proident voluptate ex est mollit. Sunt mollit excepteur ea ad ut ea id
        in labore eu tempor pariatur id do. Ad veniam ex veniam nulla do nulla
        amet labore quis do duis labore. Duis culpa reprehenderit commodo
        proident dolor. Pariatur anim nostrud reprehenderit ipsum adipisicing
        enim nostrud officia consectetur labore consequat labore occaecat esse.
        Minim nisi tempor voluptate ullamco eiusmod aliqua. Qui cupidatat culpa
        Lorem proident pariatur consequat sit excepteur do. Anim est est laborum
        quis pariatur aute proident laboris sunt exercitation ipsum. Dolore quis
        aliquip occaecat officia non dolore veniam. Velit ipsum laboris eu ipsum
        enim enim anim ea enim id consequat minim tempor velit fugiat. Velit
        nulla nostrud elit ex in in aliquip Lorem laboris minim eiusmod deserunt
        culpa sit tempor. Eu amet enim sunt culpa veniam. In esse esse nisi
        deserunt quis ea eu ex dolor ut eiusmod non do. Cupidatat non laboris
        qui dolor ea. Aute cillum elit proident dolor sit sit in et sit ad
        occaecat ut. Eiusmod eu ullamco ullamco amet elit ad ad consequat. Sit
        deserunt in cupidatat non minim aliquip elit. Sint aute elit cupidatat
        fugiat ad. Aliquip est culpa mollit culpa duis laborum commodo sunt ad.
        Anim in mollit cillum amet Lorem anim qui occaecat elit officia esse
        laborum eu laboris ex.
      </p>
    </details>
  );
});
